### ISSUE TITLE
Training Data Generation: DCGANs

### ISSUE THREAD

**Issue by rrbutani** [ut-ras/rs-sw#13]
### what

Starting with the imagery teams have shared from the 2019 competition:
- [UWRT](https://drive.google.com/drive/folders/1GQGi8lUYJh9b7z8Vytbuw29p9ZR7L-31?usp=sharing)
- [Tartan AUV](https://drive.google.com/drive/folders/1JvenX0QeLXTte0-8ZzmQI206BZP7FQYp)
- [VladBolotov?](https://drive.google.com/file/d/1rfZt29crhoTUQMLeOpAhtyXmynbejHph/view)
- [Duke](https://drive.google.com/drive/folders/1bLXE65Dwq0K95ePldaUOyT9JdhaMq1XR?usp=sharing)
- [ARVP (University of Alberta)](https://drive.google.com/open?id=1uA61816O1yY6wxAIXrqAA5xcvAT_yLRq)

Sort, crop, and label a representative set of the images from the links above and then train a DCGAN to produce new training data.

### steps

- [ ] Work with the folks working on #14 to settle on a list of things to classify from the 2019 game. These will be the classification classes.
- [ ] Partition off part (25%?) of the data that the folks working on #15 extracted from the links above for validation (with the people working on #14 and #15).
- [ ] Start creating sorted, cropped, and labeled images from the training data; work with the people on #14 and #15 and follow the format the folks on #15 created. This will be an on-going thing; label enough data to get started for now.
- [ ] Train the generator?
  + [ ] ???
  + [ ] repeat
- [ ] Once we're happy with how the generator(s?) perform, start generating new training data.

### open questions

- DCGANs? or something else. What's the plan @sahiljain11 @s-imoni.
- I know very little about DCGANs. Would we want a separate generator/discriminator pair per object class?

**Comment by rrbutani** [comment]
@sahiljain11 @s-imoni Feel free to change the steps above but please try to keep them up to date.

**Comment by rrbutani** [comment]
@sahiljain11 can you migrate to this repo?

`feat-assisted-training-gen` as the branch name; `tools/vision/<whatever you want to call this thing>` as the folder.

**Comment by sahiljain11** [comment]
Yup. I'll do it later tonight

**Comment by sahiljain11** [comment]
Also, DCGANs has a discriminator classifier, so we don't need a separate model for each object. As of right now, we're just working on a binary classification model, but we can expand later on using the one vs. all technique
