### ISSUE TITLE
Training Data Generation: Manually

### ISSUE THREAD

**Issue by rrbutani** [ut-ras/rs-sw#14]
### what
We also want to try generating training data procedurally (the old fashioned way).

Here are some links that have the art and images for the things we'd probably want to classify:
- [Task Images](https://robonationforum.vbulletin.net/forum/robosub/-2019-robosub/1708-task-images)
- [Crucifix and Garlic Drawings](https://robonationforum.vbulletin.net/forum/robosub/-2019-robosub/1712-crucifix-and-garlic-drawings)
- [Stake Through the Heart Drawing](https://robonationforum.vbulletin.net/forum/robosub/-2019-robosub/1637-stake-through-heart-drawing)
- [Expose to Sunlight Drawing](https://robonationforum.vbulletin.net/forum/robosub/-2019-robosub/1750-expose-to-sunlight-drawing)
- [Garlic Drop Images](https://robonationforum.vbulletin.net/forum/robosub/-2019-robosub/1556-garlic-drop-images)
- [Stake Through the Heart Images](https://robonationforum.vbulletin.net/forum/robosub/-2019-robosub/1558-stake-through-heart-images)
- [Buoy Images](https://robonationforum.vbulletin.net/forum/robosub/-2019-robosub/1554-buoy-images)
- [Vampire Images](https://robonationforum.vbulletin.net/forum/robosub/-2019-robosub/1708-task-images)

We probably want to use the above images in the generated training data. Or not! Up to y'all.

### steps
- [ ] Work with the people on #13 to settle on a list of things to classify from the 2019 game. These will be the classification classes. (See: #16)
- [ ] Partition off part (25%?) of the data that the folks working on #15 extracted from the links above for validation (with the people working on #13 and #15).
- [ ] Identify all the different parameters that we want to be able to tweak in generating the images. Here are some, to start:
  + Rotation
  + Relative size (i.e. zoom; how much of the image does the target occupy)
  + Discoloration
  + Glare
- [ ] Start putting together an image generator
  + The interface should roughly be: given an object class (and, optionally, some tunables), generate images of that object class.
- [ ] Once it's functional enough, start testing it against the testing harness in #15.
  + Again, #15 should initially take a corpus of training data (which the tool in this project will generate) and return a score (from a MobileNetV2 SSD model trained on the given data and score against the validation images).
  + [ ] Tweak the tool, rinse, repeat.

It's hard to know before hand how good is 'good enough' (as in, when do we stop tweaking the tool?). For now at least, the goal is demonstrating that this style of training models is viable (as such, we're intentionally ignoring the other ways we could improve scores -- trying different models, for example).

### where
branch: `feat-manual-training-gen`

### open questions
- The main question is what parameters do we want to have for this tool.
- This tool also needs a name.
- Also:
  + How do we make things look like they're underwater?
  + Should we do the fish-eye thing?
  + How to emulate glare?
  + How about depth?
  + Properties of the water? (clear, murky, etc.)
  + We might have lights on our sub; how would we emulate that?
